### ISSUE TITLE
Review DwC mapping

### ISSUE THREAD

**Issue by damianooldoni** [riparias/anb-crayfishes-occurrences#13]
Hi @peterdesmet, @LienReyserhove! The mapping of this static dataset is ready. I would like to have your review on the mapping before @LienReyserhove can publish the dataset on GBIF.

**Comment by peterdesmet** [comment]
## Event

- [x] license: is CC BY-NC requested by ANB?
- [x] accessRights: not really applicable here, would drop the term
- [x] datasetName: `Monitoring of invasive alien crayfishes in the Flemish part of the LIFE RIPARIAS areas` I assume that is the title that fits the scope the best?
- [x] locationID: it seems like each event has its own `locationID`. You typically want locationIDs to represent the groups of unique lat/long. If that cannot be done, I would drop the term
- [x] continent: same remark as pov-ias-plants, might want to drop this term
- [x] stateProvince: although valid according to DwC definition, we have never populated this with `Flanders`... @dimevil, do you think we should?
- [x] verbatimLocalityProperty: rename to  `locality` (not even verbatim)
- [x] verbatimLatitute/longitude: all end with a `.`, should be removed

## occurrence

- [x] recordedBy: could be added with same value as `institutionCode`, but not a big fan of this so ok to leave it out
- [x] occurrenceRemarks: move after occurrenceStatus
- [x] taxonRank: add term, can be fixed `species`
- [x] vernacularName: maybe good to add this for this dataset

**Comment by damianooldoni** [comment]
Thanks @peterdesmet for the detailed review! Very much appreciated. Here below some answers to your questions

- `license`: is CC BY-NC requested by ANB? Not really. I set it to CC0 👍 
- `datasetName`: Monitoring of invasive alien crayfishes in the Flemish part of the LIFE RIPARIAS areas I assume that is the title that fits the scope the best? Well, I tried to fit it as best as I could. ANB is not mentioned in the title, but I think mentioning the organisation in the title is not a must. I am open for better titles of course.
- `stateProvince`: indeed, in VMM rattenapp dataset we used the province actually (East Flanders etc.)
- `vernacularName`: the dataset doesn't contain vernacular names for the crayfishes, only scientific names. The vernacular names are only used to refer to bycatch mentioned in the remarks (see #6), which actually I don't map

**Comment by peterdesmet** [comment]
Ok, sounds all good

**Comment by damianooldoni** [comment]
I will also round lambert coordinates as not all of them end with a dot, some of them have decimals.
Also adding `'Lambert coordinates'  AS verbatimCoordinateSystem` in sql mapping. Same as in POV IAS plants.

**Comment by damianooldoni** [comment]
`stateProvince` set in comment (= removed from mapping) until better discussed with @DimEvil.

**Comment by DimEvil** [comment]
Would maybe use in this case, as the geographical scope is Flanders. But
off course it is also like that in many other datasets... So I open the
question again... Add it in the focus Flemish datasets or don't use it
anywhere.

Op vr 14 okt. 2022 17:11 schreef Damiano Oldoni ***@***.***>:

**Comment by damianooldoni** [comment]
Thanks @DimEvil for your two cents 👍 
Few days ago @SanderDevisscher asked me whether it was possible to get data in Flanders from GBIF by specifying `Flanders` in a specific field. I said: officially yes, practically not as `stateProvince` is not used consistently. 

My opinion is to start using this field in the right way. For datasets already on GBIF, every time they have to be republished, remember to map `stateProvince` = `Flanders`.

@peterdesmet, @LienReyserhove, @DimEvil: if you all agree about this strategy, I will add `stateProvince` back in the mapping.

**Comment by peterdesmet** [comment]
I don’t think this is a good approach for getting data from Flanders (you will miss datasets we don’t have control over). Rather, use the gadm filter in GBIF: https://www.gbif.org/occurrence/search?occurrence_status=present&gadm_gid=BEL.2_1

I would keep the stateProvince field for actual provinces for our datasets (as we have done so far) and not include it for this dataset

**Comment by damianooldoni** [comment]
Wow! This filter is great. Thans @peterdesmet. Then I agree with you to leave this field empty and fill it in with the Flemish provinces if needed.

**Comment by damianooldoni** [comment]
Close as completed.
