### ISSUE TITLE
Set publisher

### ISSUE THREAD

**Issue by damianooldoni** [riparias/anb-crayfishes-occurrences#9]
I asked ANB whether they would like to become a GBIF publisher.
Their choice could take a while of course. I asked to Dimi today and it seems that we can still publish this dataset as a INBO dataset if we are ready to publish this dataset. Changing publisher has no influence on occurrenceID and datasetID.

**Comment by damianooldoni** [comment]
Although ANB is still not an official publisher on GBIF, i set `'ANB'` as `rightsHolder` and `institutionCode` in the event core. @peterdesmet: do I right?

**Comment by peterdesmet** [comment]
- rightsHolder: yes
- institutionCode: debatable, but I guess yes

**Comment by damianooldoni** [comment]
Thanks.

**Comment by damianooldoni** [comment]
ANB is a publisher now: https://www.gbif.org/publisher/d2b220bd-5701-4fe4-ba06-a1e3fc6288fe
